#!/bin/bash

# Default MSVC version is "17".
if [ -z "$CCCL_MSVC_WINE_BUILD_INSTALL_MSVC" ]; then
    CCCL_MSVC_WINE_BUILD_INSTALL_MSVC="17"
fi

CCCL_MSVC_WINE_BUILD_INSTALL_SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
CCCL_MSVC_WINE_BUILD_INSTALL_CCCL_MSVC_WINE_DIR="$(realpath --canonicalize-missing --no-symlinks "$CCCL_MSVC_WINE_BUILD_INSTALL_SCRIPT_DIR/..")"
CCCL_MSVC_WINE_BUILD_INSTALL_CCCL_MSVC_WINE_BUILD_DIR="$CCCL_MSVC_WINE_BUILD_INSTALL_CCCL_MSVC_WINE_DIR/.build"
CCCL_MSVC_WINE_BUILD_INSTALL_CCCL_MSVC_WINE_DONE_DIR="$CCCL_MSVC_WINE_BUILD_INSTALL_CCCL_MSVC_WINE_DIR/.done"
CCCL_MSVC_WINE_BUILD_INSTALL_CCCL_MSVC_WINE_INSTALL_DIR="$CCCL_MSVC_WINE_BUILD_INSTALL_CCCL_MSVC_WINE_DIR/install"

# Build "msvc-wine".
CCCL_MSVC_WINE_BUILD_INSTALL_MSVC_PROJECT_NAME="msvc-wine-$CCCL_MSVC_WINE_BUILD_INSTALL_MSVC"
if ! test -f "$CCCL_MSVC_WINE_BUILD_INSTALL_CCCL_MSVC_WINE_DONE_DIR/$CCCL_MSVC_WINE_BUILD_INSTALL_MSVC_PROJECT_NAME"; then
    CCCL_MSVC_WINE_BUILD_INSTALL_CCCL_MSVC_WINE_INSTALL_MSVC_WINE_DIR="$CCCL_MSVC_WINE_BUILD_INSTALL_CCCL_MSVC_WINE_INSTALL_DIR/$CCCL_MSVC_WINE_BUILD_INSTALL_MSVC_PROJECT_NAME"
    CCCL_MSVC_WINE_BUILD_INSTALL_CCCL_MSVC_WINE_INSTALL_MSVC_WINE_TOOLCHAIN_DIR="$CCCL_MSVC_WINE_BUILD_INSTALL_CCCL_MSVC_WINE_INSTALL_MSVC_WINE_DIR/toolchain"
    CCCL_MSVC_WINE_BUILD_INSTALL_CCCL_MSVC_WINE_INSTALL_MSVC_WINE_WINEPREFIX_DIR="$CCCL_MSVC_WINE_BUILD_INSTALL_CCCL_MSVC_WINE_INSTALL_MSVC_WINE_DIR/wineprefix"
    
    echo "Building and installing \"$CCCL_MSVC_WINE_BUILD_INSTALL_MSVC_PROJECT_NAME\" project..."
    
    # Remove previous failed build and install directories and recreate the empty directories.
    rm -rf "$CCCL_MSVC_WINE_BUILD_INSTALL_CCCL_MSVC_WINE_INSTALL_MSVC_WINE_TOOLCHAIN_DIR"
    rm -rf "$CCCL_MSVC_WINE_BUILD_INSTALL_CCCL_MSVC_WINE_INSTALL_MSVC_WINE_WINEPREFIX_DIR"
    mkdir -p "$CCCL_MSVC_WINE_BUILD_INSTALL_CCCL_MSVC_WINE_INSTALL_MSVC_WINE_TOOLCHAIN_DIR"
    mkdir -p "$CCCL_MSVC_WINE_BUILD_INSTALL_CCCL_MSVC_WINE_INSTALL_MSVC_WINE_WINEPREFIX_DIR"
    
    
    # Build and install.
    cd "$CCCL_MSVC_WINE_BUILD_INSTALL_CCCL_MSVC_WINE_DIR/src/msvc-wine"
    if ! [ -z "$WINEPREFIX" ]; then
        CCCL_MSVC_WINE_BUILD_INSTALL_CCCL_MSVC_WINE_INSTALL_MSVC_OLD_WINE_WINEPREFIX_DIR="$WINEPREFIX"
    fi
    WINEPREFIX="$CCCL_MSVC_WINE_BUILD_INSTALL_CCCL_MSVC_WINE_INSTALL_MSVC_WINE_WINEPREFIX_DIR"
    ./vsdownload.py --dest "$CCCL_MSVC_WINE_BUILD_INSTALL_CCCL_MSVC_WINE_INSTALL_MSVC_WINE_TOOLCHAIN_DIR" --major "$CCCL_MSVC_WINE_BUILD_INSTALL_MSVC" --accept-license
    ./install.sh "$CCCL_MSVC_WINE_BUILD_INSTALL_CCCL_MSVC_WINE_INSTALL_MSVC_WINE_TOOLCHAIN_DIR"
    if [ -z "$CCCL_MSVC_WINE_BUILD_INSTALL_CCCL_MSVC_WINE_INSTALL_MSVC_OLD_WINE_WINEPREFIX_DIR" ]; then
        unset WINEPREFIX
    else
        WINEPREFIX="$CCCL_MSVC_WINE_BUILD_INSTALL_CCCL_MSVC_WINE_INSTALL_MSVC_OLD_WINE_WINEPREFIX_DIR"
        unset CCCL_MSVC_WINE_BUILD_INSTALL_CCCL_MSVC_WINE_INSTALL_MSVC_OLD_WINE_WINEPREFIX_DIR
    fi
    cd -
    
    # Record "done".
    mkdir -p "$CCCL_MSVC_WINE_BUILD_INSTALL_CCCL_MSVC_WINE_DONE_DIR"
    touch "$CCCL_MSVC_WINE_BUILD_INSTALL_CCCL_MSVC_WINE_DONE_DIR/$CCCL_MSVC_WINE_BUILD_INSTALL_MSVC_PROJECT_NAME"
    
    echo "Done building and installing \"$CCCL_MSVC_WINE_BUILD_INSTALL_MSVC_PROJECT_NAME\" project."
fi

# Build "cccl".
if ! test -f "$CCCL_MSVC_WINE_BUILD_INSTALL_CCCL_MSVC_WINE_DONE_DIR/cccl"; then
    CCCL_MSVC_WINE_BUILD_INSTALL_CCCL_MSVC_WINE_BUILD_CCCL_DIR="$CCCL_MSVC_WINE_BUILD_INSTALL_CCCL_MSVC_WINE_BUILD_DIR/cccl"
    CCCL_MSVC_WINE_BUILD_INSTALL_CCCL_MSVC_WINE_INSTALL_CCCL_DIR="$CCCL_MSVC_WINE_BUILD_INSTALL_CCCL_MSVC_WINE_INSTALL_DIR/cccl"
    
    echo "Building and installing \"cccl\" project..."
    
    # Remove previous failed build and install directories and recreate the empty directories.
    rm -rf "$CCCL_MSVC_WINE_BUILD_INSTALL_CCCL_MSVC_WINE_BUILD_CCCL_DIR"
    rm -rf "$CCCL_MSVC_WINE_BUILD_INSTALL_CCCL_MSVC_WINE_INSTALL_CCCL_DIR"
    mkdir -p "$CCCL_MSVC_WINE_BUILD_INSTALL_CCCL_MSVC_WINE_BUILD_CCCL_DIR"
    mkdir -p "$CCCL_MSVC_WINE_BUILD_INSTALL_CCCL_MSVC_WINE_INSTALL_CCCL_DIR"
    
    # Bootstrap.
    cd "$CCCL_MSVC_WINE_BUILD_INSTALL_CCCL_MSVC_WINE_DIR/src/cccl"
    ./bootstrap
    cd -
    
    # Build and install.
    cd "$CCCL_MSVC_WINE_BUILD_INSTALL_CCCL_MSVC_WINE_BUILD_CCCL_DIR"
    "$CCCL_MSVC_WINE_BUILD_INSTALL_CCCL_MSVC_WINE_DIR/src/cccl/configure" --prefix="$CCCL_MSVC_WINE_BUILD_INSTALL_CCCL_MSVC_WINE_INSTALL_CCCL_DIR"
    make install
    cd -
    
    # Cleanup.
    cd "$CCCL_MSVC_WINE_BUILD_INSTALL_CCCL_MSVC_WINE_DIR/src/cccl"
    rm -rf Makefile.in aclocal.m4 autom4te.cache configure install-sh missing
    cd -
    
    # Record "done".
    mkdir -p "$CCCL_MSVC_WINE_BUILD_INSTALL_CCCL_MSVC_WINE_DONE_DIR"
    touch "$CCCL_MSVC_WINE_BUILD_INSTALL_CCCL_MSVC_WINE_DONE_DIR/cccl"
    
    echo "Done building and installing \"cccl\" project."
fi
